### ISSUE TITLE
Investigate Crash On Adding New Report

### ISSUE THREAD

**Issue by antikathistemi** [ushahidi/Ushahidi_iPhone#3]
I experience the app crashing when trying to add a new report (plus button)

App Version: 1.12
Device Model: iPhone
Device Version: 5.0.1

**Comment by dalezak** [comment]
This problem is fixed in new version.

**Comment by mrblog** [comment]
It still crashes for me. I don't want to start experimenting with the app if the base version without any mods doesn't work:

Test
2013-01-15 20:21:53.279 Ushahidi[39560:16403] -[USHReportMapViewController mapView:viewForAnnotation:] [Line 127] Test
2013-01-15 20:22:29.572 Ushahidi[39560:16403] -[USHHeaderView paddingForTable:] [Line 72] Parent:320.000000 Width:320.000000
2013-01-15 20:22:32.487 Ushahidi[39560:16403] -[USHHeaderView paddingForTable:] [Line 72] Parent:320.000000 Width:320.000000
2013-01-15 20:22:51.917 Ushahidi[39560:16403] -[USHViewController viewWillDisappear:] [Line 264] USHReportMapViewController_iPad
2013-01-15 20:22:51.918 Ushahidi[39560:16403] -[USHReportTabBarController tabBarController:didSelectViewController:] [Line 304] UIViewController
2013-01-15 20:22:51.919 Ushahidi[39560:16403] -[USHViewController viewDidDisappear:] [Line 270] USHReportMapViewController_iPad

Simulator: iPad iOS 5.0 (same problem iOS 6)

**Comment by dalezak** [comment]
Thanks for reporting this issue, I'll investigate and include a fix ASAP.

**Comment by dalezak** [comment]
Re-opened issue.

**Comment by dalezak** [comment]
Hey David, I have been unable to recreate this problem.

I've tested on the iPad Simulator for iOS 5.0 (http://o7.no/X18O3H), iOS 5.1 (http://o7.no/X18KAV) and iOS 6.0 (http://o7.no/TEOBGf).

Any additional information you can provide that could help identify cause of the crash?

**Comment by mrblog** [comment]
Thanks. Unfortunately, it looks like those Dropbox links have expired. I removed the X code project and started fresh and did nothing but Build/Run. I guess it isn't crashing, but the Report option doesn't do anything. It gives a black screen and the console shows the following:

2013-01-26 22:22:22.147 Ushahidi[49149:16403] -[USHViewController viewWillAppear:] [Line 251] USHReportMapViewController_iPad
2013-01-26 22:22:22.234 Ushahidi[49149:16403] -[USHReportTabBarController tabBarController:didSelectViewController:] [Line 292] USHReportMapViewController
2013-01-26 22:22:22.235 Ushahidi[49149:16403] -[UIViewController(USH) barButtonWithItems:] [Line 104] Nib:USHReportTabBarController Items:3 Width:88.000000 
2013-01-26 22:22:22.238 Ushahidi[49149:16403] -[USHViewController viewDidAppear:] [Line 257] USHReportMapViewController_iPad
2013-01-26 22:22:29.729 Ushahidi[49149:16403] -[USHViewController viewWillDisappear:] [Line 264] USHReportMapViewController_iPad
2013-01-26 22:22:29.730 Ushahidi[49149:16403] -[USHReportTabBarController tabBarController:didSelectViewController:] [Line 304] UIViewController
2013-01-26 22:22:29.731 Ushahidi[49149:16403] -[USHViewController viewDidDisappear:] [Line 270] USHReportMapViewController_iPad

It doesn't let the user enter a report. Is this the correct behavior? 

There are build warnings:
Ushahidi_iPhone-master/App/Classes/Models/USHSettings.m:34:1: Casting 'volatile USHSettings *' to type 'USHSettings *' discards qualifiers

ld: warning: directory not found for option '-FUshahidi_iPhone-master/App/Libraries'

There is no App/Libraries from the archive, as is.  I created a symlink to ../SDK/Libraries and got rid of that warning, but the Report option still just gives a blank/black screen.

![iOS Simulator Screen shot Jan 26 2013 10 25 44 PM](https://f.cloud.github.com/assets/403589/100668/f128280e-684a-11e2-99e9-bfeb2cce70d2.png)

**Comment by dalezak** [comment]
Ah-ha! I thought something weird was happening.

I believe it's related to the location of the Ushahidi.SDK library project.

I had problems getting the App project to find the SDK project, so referenced the location as absolute path.

I'll investigate changing it to relative path which hopefully fixes your problem.

**Comment by isaaclimdc** [comment]
I don't believe this problem exists in the current build anymore.
